// <auto-generated />
using BookApp2.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookApp2.Repository.Migrations
{
    [DbContext(typeof(BookAppDbContext))]
    partial class BookAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookApp2.Repository.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<int>("CatalogueId");

                    b.Property<string>("Genre");

                    b.Property<int>("Price");

                    b.Property<string>("Publisher");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("CatalogueId");

                    b.ToTable("Books");

                    b.HasData(
                        new { Id = 1, Author = "Joe", CatalogueId = 1, Genre = "Programmoig", Price = 200, Publisher = "Aprex", Title = "C# Learing" },
                        new { Id = 2, Author = "Alex", CatalogueId = 1, Genre = "Database", Price = 220, Publisher = "Oracle Publication", Title = "PL/SQL Learing" }
                    );
                });

            modelBuilder.Entity("BookApp2.Repository.Catalogue", b =>
                {
                    b.Property<int>("CatalogueId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("CatalogueId");

                    b.ToTable("Catalogues");

                    b.HasData(
                        new { CatalogueId = 1, Name = "CSE" }
                    );
                });

            modelBuilder.Entity("BookApp2.Repository.Book", b =>
                {
                    b.HasOne("BookApp2.Repository.Catalogue")
                        .WithMany("Books")
                        .HasForeignKey("CatalogueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
